export const MAX_PLAINTEXT_BYTES = 100 * 1024;
export const AES_GCM_AUTH_TAG_BYTES = 16;
export const MAX_CIPHERTEXT_BYTES =
  MAX_PLAINTEXT_BYTES + AES_GCM_AUTH_TAG_BYTES;
export const MAX_SHARE_REQUEST_BODY_BYTES = 140 * 1024;
export const MAX_REPORT_REQUEST_BODY_BYTES = 8 * 1024;
